### ISSUE TITLE
Sample APK(ApkTest) is downloaded

### ISSUE THREAD

**Issue by adolfdsilva** [rgroult/MobDistTool#12]
Hi,

I've created a release and uploaded my test apk.. The apk size is around 4MB.. But the downloaded apk is around 490 KB.. When I install the apk a TestApk is launched... And I get below error on the server logs. Any ides?

ERROR - 2017-10-09 02:43:44.961672
Asynchronous error
HttpException: Content size below specified contentLength.  497449 bytes written but expected 4227809., uri = /api/in/v1/artifacts/989be8d6-28a8-478c-93f2-256c5b60a3e1/file?token=3732ddd092a88a9ada9a065ec3e207a9
dart:isolate  _RawReceivePortImpl._handleMessage

<img width="350" alt="screen shot 2017-10-09 at 9 49 37 am" src="https://user-images.githubusercontent.com/6647993/31323890-6322a72e-acd7-11e7-9ef3-4ec6da0cd048.png">

**Comment by rgroult** [comment]
Hi
The default artifact storage in docker image is the "Yes storage". It can't be used to test install on real devices. Configure your storage to another mode :
https://github.com/rgroult/MobDistTool#configuration
