### ISSUE TITLE
Docker Build Fail due to SocketException

### ISSUE THREAD

**Issue by westhacker** [rgroult/MobDistTool#3]
Bonjour, I am really appreciating your works. I tried to deploy **MobDistTool** by docker in Digital Ocean. I used the **docker pre-built images**. However, a **SocketException** error occurs when initializing the mongodb.

![capture](https://cloud.githubusercontent.com/assets/4177049/16375890/f6c04838-3c5d-11e6-80ea-7c7dee27d7ca.PNG)

Could you help me with this error? Thanks in advance !

**Comment by rgroult** [comment]
Hi
The prebuild docker images doesn't contain mongoDB database. You need a mongoDB container and link it to the MDT docker image image (with env value parameters).

**Comment by westhacker** [comment]
Thanks for your reply. 

I have a mongoDB container named "mongo", and I used the following command:

`$ docker run --name mdt --link mongo:mongo -p 80:80 rgroult2/mobdisttool`

It gave the same error above. Do I need add some other parameters ?

**Comment by rgroult** [comment]
You need to configure MDT docker image through environment variables . @see https://github.com/rgroult/MobDistTool#configuration
For mongoDB add a en variable "MDT_DATABASE_URI" set to "mongodb://yourmongodbcontainer:27017/mdt_dev"
