### ISSUE TITLE
HttpException: Content size below specified contentLength

### ISSUE THREAD

**Issue by 0x5e** [rgroult/MobDistTool#4]
hello, I was trying to install ios app in iphone and failed with following error

```
2016-07-22 14:13:17:[App/0] ERROR - 2016-07-22 06:13:17.481332
2016-07-22 14:13:17:[App/0] Asynchronous error
2016-07-22 14:13:17:[App/0] HttpException: Content size below specified contentLength. 2825 bytes written but expected 6951837., uri = /api/in/v1/artifacts/cec27d95-e438-4fe9-a705-3eb472248a66/file?token=4c3678b9b99577dc27e1f39d2c737b61
2016-07-22 14:13:17:[App/0] dart:isolate _RawReceivePortImpl._handleMessage
```

by the way, `MDT_SERVER_URL` not mentioned in readme, so delpoy function can't be used if server is not run in local. ^_^

**Comment by rgroult** [comment]
Hi.
I updated README for missing configuration keys.
What is your storage artifact manager configuration ? 
It's seems you are using the "yes storage" manager which never store artifact and always return the same sample file. It can't be use to install app, only to test server (accounts, upload, delete, etc..)

Maybe the default artifat manager should be the "local storage" manager.

**Comment by 0x5e** [comment]
oh yes, I'm using "yes storage", sorry ...
another question, is about the qrcode, maybe android device scan the qrcode can directly download the apk, but ipa can't? I'm in china, we usually use wechat to scan qrcode, then wechat will open a webpage with text "itms-services://?action=download-manifest&url=xxxxxx" whitch is unclickable... maybe the qrcode url is a download page will be better?

**Comment by rgroult** [comment]
The QrCode is not a download link, it's a install link. On Android it is the same but on IOS, the format is **itms-service://...**  [(see Here).](http://www.aymericlamboley.fr/blog/install-an-ipa-on-ios-directly-from-a-url/)
Sometimes QRCode readers are unable to handle correctly **itms-services://** scheme. 
I use  [QR Code](https://itunes.apple.com/fr/app/qrcode-the-delightful-reader/id948489462?l=en&mt=8) which works great.

**Comment by 0x5e** [comment]
ok, thanks :)
