### ISSUE TITLE
[Need help] Setup MDT server with https 

### ISSUE THREAD

**Issue by tantam** [rgroult/MobDistTool#5]
I have set up MDT successfully with port 8080, but I can not install iOS app, because iOS does not allow install app without https url.

So I try to change port from 8080 to 8443 but it is not working.

Can anyone help me to build MDT with https connetion

**Comment by rgroult** [comment]
There is another problem with iOS OTA Install: You need a valid https certificate, not a auto signed one. In production, I use a nginx server with let's encrypt https certificates as a reverse proxy to be able to use iOS OTA Install, I suggest you to do the same.  
If you want absolutely use MDT to provides https, you need to modify it to handle https certificates.

**Comment by tantam** [comment]
thanks, I intend to use https certificates on cloudflare.com instead of using let's encrypt https certificates, is it ok right ?

**Comment by tantam** [comment]
I tried with Cloudflare but it did not work, so I move to letsencripts and it works.

Anyway, thanks for your hardwork with this one.

Regards.
