### ISSUE TITLE
Can't run the docker container

### ISSUE THREAD

**Issue by yaoweijie** [rgroult/MobDistTool#9]
Hi

I am having issues running the docker container.

I have already installed mongo and comment the bind ip setting, hence allowing the mongodb to be connected from all interfaces. 

Appreciate the assitance

===== TERMINAL OUTPUT =====
[root@ip-10-0-0-121 ~]# docker run -i -t 6b2847c9dc09 /bin/bash
Observatory listening on http://0.0.0.0:8181/
[2017-07-11 08:56:29.439077] INFO RPC: MDT starting ...
[2017-07-11 08:56:29.444843] INFO RPC: logging file : mdt_logs_20170711.txt
[2017-07-11 08:56:29.446405] INFO RPC: mongo located on  mongodb://localhost:27017/mdt_dev
[2017-07-11 08:56:29.447208] INFO RPC: mongo initializing... 
[2017-07-11 08:56:29.472770] INFO RPC: mongo initializing failed [SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 49804], waiting 3 secs before next try ..
[2017-07-11 08:56:32.474346] INFO RPC: mongo located on  mongodb://localhost:27017/mdt_dev
[2017-07-11 08:56:32.474780] INFO RPC: mongo initializing... 
[2017-07-11 08:56:32.476917] INFO RPC: mongo initializing failed [SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 49808], waiting 3 secs before next try ..
^C[root@ip-10-0-0-121 ~]# 
[root@ip-10-0-0-121 ~]# 
[root@ip-10-0-0-121 ~]# 
===== TERMINAL OUTPUT =====

**Comment by rgroult** [comment]
Hi

It's seems you have a problem with your config: mongo located on mongodb://localhost:27017/mdt_de
"localhost" in MDT container is himself, not your host.
How did you installed mongoDB ? docker or natively ? 
- Docker: you need to link your MDT container to mongoDB container (@see --link in docker documentation)
- Natively : use your host IP to reach mongoDB

**Comment by adolfdsilva** [comment]
Hi,

I'm getting the same error, can you help me to link mongo db to mdt..
I'm starting the mongo db in docker using below command

>  docker run --name mdt-mongo mongo

And linking MDT container to it by using

> docker run --name mdt-app1 --link mdt-mongo:mongo -d rgroult2/mobdisttool

But I still get Connection Refused error like above.

**Comment by adolfdsilva** [comment]
Ok, So you have 2 options(assuming you're using mongo db on docker ). Second one is just a work around.

1. Redefine the uri "MDT_DATABASE_URI":"mongodb://#CONAINER_NAME#:27017/mdt_dev" and rebuilt the docker image. Then run your mongo container with same #CONTAINER_NAME#. Lastly run you MDT container and link it to mongo db container.

2. #LazyWay:)
Run mongo db as below

> docker run --name localhost mongo
  
And then run 

> docker run --name mdt-app1 --link localhost:mongo -p 8080:8080 rgroult2/mobdisttool

The mongo db container name("localhost") is the same which is configured already in the docker image.

Hope this helps!!!

**Comment by rgroult** [comment]
Hi
If you run mongo with `docker run --name mdt-mongo mongo`

Run MDT with docker `run --name mdt-app1 -e "MDT_DATABASE_URI=mongodb://mongo/mobdisttool" --link mdt-mongo:mongo  rgroult2/mobdisttool`

The` --link `option is to make dns alias container world. In your case the hostname "mongo" is wrapped on the mongodb container.

The `-e` is to provide env value. Each config value can be overridden by env.
See all config keys : https://github.com/rgroult/MobDistTool#configuration

**Comment by adolfdsilva** [comment]
Ok thanks for the reply... This was the first time I was using docker
